# Site settings
title: Blogging Freelancer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Graphic Artist - User Experience Designer
baseurl: "/jekyll-blogging-freelancer" # the subpath of your site, e.g. /blog
url: "https://mewa.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: SBootstrap
github_username:  mewa
facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: 3034 Melrose Place
address_city: Beverly Hills
address_state: CA
address_zip: 90201

# Build settings
markdown: kramdown

source: "intermediate"

destination: "jekyll"

collections:
  portfolio:
    output: false

gems: 
  - jekyll-paginate
  - jekyll-feed

permalink: "blog/:year/:slug/"
paginate: 5
paginate_path: "/blog/posts/page:num/"

excerpt_separator: "<!--more-->"